## <span style="color:#FFC1C1; font-weight:bold">1. 텐서 (Tensors)</span>

* 데이터 표현을 위한 기본 구조로 텐서(tensor)를 사용
* 텐서는 데이터를 담기위한 컨테이너(container)로서 일반적으로 수치형 데이터를 저장
* 넘파이(NumPy)의 ndarray와 유사
* GPU를 사용한 연산 가속 가능

### 01. 텐서 초기화


**데이터로부터 직접(directly) 생성하기**

데이터로부터 직접 텐서를 생성할 수 있습니다. 데이터의 자료형(data type)은 자동으로 유추합니다.

In [2]:
import torch
#Tensor 데이터를 담는 컨테이너

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

**NumPy 배열로부터 생성하기**

텐서는 NumPy 배열로 생성할 수 있습니다. (반대도 가능)
Array-like 데이터를 사용해 새 텐서를 선언해줄 수 있습니다.

In [3]:
import numpy as np

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)


**NumPy 변환(Bridge)**
CPU 상의 텐서와 NumPy 배열은 메모리 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경됩니다.



In [8]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


텐서의 변경 사항이 NumPy 배열에 반영됩니다.

In [9]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


**다른 텐서로부터 생성하기:**

명시적으로 재정의(override)하지 않는다면, 인자로 주어진 텐서의 속성(모양(shape), 자료형(datatype))을 유지합니다.

In [10]:
x_ones = torch.ones_like(x_data) # x_data의 속성을 유지합니다.
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # x_data의 속성을 덮어씁니다.
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.3302, 0.8427],
        [0.7840, 0.4667]]) 



**무작위(random) 또는 상수(constant) 값을 사용하기:**

``shape`` 은 텐서의 차원(dimension)을 나타내는 튜플(tuple)로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.

In [11]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4503, 0.2784, 0.7541],
        [0.4151, 0.2315, 0.1533]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


---------------

### 02. 텐서의 속성(attribute)



텐서의 속성은 텐서의 모양(shape), 자료형(datatype) 및 어느 장치에 저장되는지를 나타냅니다.

In [12]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


--------------

### 03. 텐서 연산 (operations)

* 텐서에 대한 수학 연산, 삼각함수, 비트 연산, 비교 연산, 집계 등 제공

In [16]:
import math 

a = torch.rand(1, 2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))    # -0.5 보다 작거나 0.5보다 큰 것은 모두 -.5, .5로

tensor([[-0.3684, -0.8265]])
tensor([[0.3684, 0.8265]])
tensor([[-0., -0.]])
tensor([[-1., -1.]])
tensor([[-0.3684, -0.5000]])


In [17]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1, 2, 3, 1, 2, 2])))

tensor([[-0.3684, -0.8265]])
tensor(-0.8265)
tensor(-0.3684)
tensor(-0.5974)
tensor(0.3239)
tensor(0.3045)
tensor([1, 2, 3])


**산술 연산(Arithmetic operations)**



In [20]:
# 두 텐서 간의 행렬 곱(matrix multiplication)을 계산합니다. y1, y2, y3은 모두 같은 값을 갖습니다.
# ``tensor.T`` 는 텐서의 전치(transpose)를 반환합니다.
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [21]:
# 요소별 곱(element-wise product)을 계산합니다. z1, z2, z3는 모두 같은 값을 갖습니다.
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

**단일-요소(single-element) 텐서** 

텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우,
``item()`` 을 사용하여 Python 숫자 값으로 변환할 수 있습니다:

In [22]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


**바꿔치기(in-place) 연산**

in-place방식으로 텐서의 값을 변경하는 연산 뒤에는 _''가 붙습니다. 
예를 들어: ``x.copy_(y)`` 나 ``x.t_()`` 는 ``x`` 를 변경합니다.



In [23]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


In [18]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([0.3731])
tensor([1.])
tensor([1.3731])


------------

### 04. 텐서 조작 (manipulations)

**NumPy식의 표준 인덱싱과 슬라이싱**

In [19]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


**텐서 합치기** 


``torch.cat`` 을 사용하여 주어진 차원에 따라 일련의 텐서를 연결할 수 있습니다.

In [24]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.],
        [6., 5., 6., 6., 6., 5., 6., 6., 6., 5., 6., 6.]])


--------------

### 05. CUDA 텐서 

기본적으로 텐서는 CPU에 생성됩니다. ``.to`` 메소드를 사용하면 (GPU의 가용성(availability)을 확인한 뒤) GPU로 텐서를 명시적으로 이동할 수 있습니다.

In [13]:
# GPU가 존재하면 텐서를 이동합니다
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [14]:
# gpu를 사용하기 위해서 cuda 라이브러리를 사용해야함 
# 텐서를 cuda로 옮기는 과정 필요 

x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.3731])
0.37310707569122314
torch.float32


In [15]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x + y 
print(z)
print(z.to('cpu', torch.double))

cpu
tensor([1.])
tensor([0.3731])
tensor([1.3731])
tensor([1.3731], dtype=torch.float64)


---------------------

### 06. Autograd(자동미분)

`torch.autograd` 패키지는 Tensor의 모든 연산에 대해 **자동 미분**을 제공합니다. 이는 코드를 어떻게 작성하여 실행하느냐에 따라 역전파가 정의된다는 뜻이죠.`backprop`를 위해 미분값을 자동으로 계산해줍니다. 

`requires_grad` 속성을 `True`로 설정하면, 해당 텐서에서 이루어지는 모든 연산들을 추적하기 시작

기록을 추적하는 것을 중단하게 하려면, `.detach()`를 호출하여 연산기록으로부터 분리

In [ ]:
a = torch.randn(3, 3)
a = a * 3
print(a)
print(a.requires_grad)  # 기본적으로 requires_grad는 false

`requires_grad_(...)`는 기존 텐서의 `requires_grad` 값을 바꿔치기(`in-place`)하여 변경

`grad_fn`: 미분값을 계산한 함수에 대한 정보 저장 (어떤 함수에 대해서 backprop 했는지)

In [ ]:
a.requires_grad_(True)
print(a.requires_grad)

b = (a*a).sum()
print(b)    # sum이라는 연산 했다는 것을 남김. # 어떤 함수에 대해 gradient 계산을 했는지 남김 
print(b.grad_fn)

#### <span style="color:#FFC1C1; font-weight:bold">자동 미분 흐름 예제</span>

- 계산 흐름 $a \rightarrow b  \rightarrow c  \rightarrow out $

## $\quad \frac{\partial out}{\partial a} = ?$
- `backward()`를 통해 $a \leftarrow b  \leftarrow c  \leftarrow out $을 계산하면 $\frac{\partial out}{\partial a}$값이 `a.grad`에 채워짐

In [15]:
a = torch.ones(2, 2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [16]:
a = torch.ones(2, 2, requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [17]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
None
None


$b = a + 2$

In [18]:
b = a + 2
b.retain_grad()
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


$c = b^2$

In [19]:
c = b ** 2
c.retain_grad()
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [20]:
out = c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [21]:
print(out)
out.backward()

tensor(36., grad_fn=<SumBackward0>)


a의 `grad_fn`이 None인 이유는 직접적으로 계산한 부분이 없었기 때문이죠! 

In [22]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])
None


In [23]:
print(b.data)
print(b.grad)
print(b.grad_fn)



tensor([[3., 3.],
        [3., 3.]])
tensor([[6., 6.],
        [6., 6.]])


In [24]:
print(c.data)
print(c.grad)
print(c.grad_fn)
c.retain_grad()


tensor([[9., 9.],
        [9., 9.]])
tensor([[1., 1.],
        [1., 1.]])


In [25]:
print(out.data)
print(out.grad)
print(out.grad_fn)

tensor(36.)
None


/var/folders/bv/pwm7yqld0kx5tnjqm191709c0000gn/T/ipykernel_3290/578081240.py:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1702400227158/work/build/aten/src/ATen/core/TensorBody.h:494.)
  print(out.grad)
